"""Add background_theme column to User model

Revision ID: 04da0c5c5e7f
Revises: a07eacdeb2ee
Create Date: 2025-05-01 18:14:15.657905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04da0c5c5e7f'
down_revision = 'a07eacdeb2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_theme', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('background_theme')

    # ### end Alembic commands ###
